from enum import Enum as __enum__

class Voice(__enum__):
    Allison = "Allison"
    Amy = "Amy"
    Belle = "Belle"
    Callie = "Callie"
    Charlie = "Charlie"
    Dallas = "Dallas"
    Damien = "Damien"
    David = "David"
    Diane = "Diane"
    Duchess = "Duchess"
    Duncan = "Duncan"
    Emily = "Emily"
    Linda = "Linda"
    Robin = "Robin"
    Shouty = "Shouty"
    Walter = "Walter"
    William = "William"
    Whispery = "Whispery"
    Lawrence = "Lawrence"
    Millie = "Millie"
    Vittoria = "Vittoria"
    Katrin = "Katrin"
    Matthias = "Matthias"
    Isabelle = "Isabelle"
    Jean_Pierre = "Jean-Pierre"
    Alejandra = "Alejandra"
    Miguel = "Miguel"
