from enum import Enum as __enum__

class Voice(__enum__):
    Conrad = 'Conrad'
    Designer = 'Designer'
    Diesel = 'Diesel'
    Dog = 'Dog'
    Evilgenius = 'Evilgenius'
    Frank = 'Frank'
    French_fry = 'French-fry'
    Gregory = 'Gregory'
    Jerkface = 'Jerkface'
    JerseyGirl = 'JerseyGirl'
    Kayla = 'Kayla'
    Kevin = 'Kevin'
    Kidaroo = 'Kidaroo'
    Princess = 'Princess'
    RansomNote = 'RansomNote'
    Robot = 'Robot'
    Shygirl = 'Shygirl'
    Susan = 'Susan'
    Tamika = 'Tamika'
    TopHat = 'TopHat'
    Vixen = 'Vixen'
    Vlad = 'Vlad'
    Warren = 'Warren'
    Wiseguy = 'Wiseguy'
    Zach = 'Zach'
    Obama = 'Obama'

