from src.pyt2s.models.BaseModel import BaseVoiceModel


class CepstralVoice(BaseVoiceModel):
    Allison = 'Allison'
    Amy = 'Amy'
    Belle = 'Belle'
    Callie = 'Callie'
    Charlie = 'Charlie'
    Dallas = 'Dallas'
    Damien = 'Damien'
    David = 'David'
    Diane = 'Diane'
    Duchess = 'Duchess'
    Emily = 'Emily'
    Linda = 'Linda'
    Robin = 'Robin'
    Shouty = 'Shouty'
    Walter = 'Walter'
    William = 'William'
    Whispery = 'Whispery'
    Lawrence = 'Lawrence'
    Millie = 'Millie'
    Duncan = 'Duncan'
    Vittoria = 'Vittoria'
    Katrin = 'Katrin'
    Matthias = 'Matthias'
    Isabelle = 'Isabelle'
    Jean_Pierre = 'Jean-Pierre'
    Alejandra = 'Alejandra'
    Miguel = 'Miguel'
    