import json as __json__
import requests as __requests__
from enum import Enum as __enum__

class Voice(__enum__):
    Jalal_HQ = "Jalal22k_HQ"
    Christinabtob_HQ = "Christinabtob22k_HQ"
    Gabriela_HQ = "Gabriela22k_HQ"
    RachelTransport_HQ = "Racheltransport22k_HQ"
    Sophiabtob_HQ = "Sophiabtob22k_HQ"
    RikkeTransport_HQ = "RikkeTransport22k_HQ"
    Tessabtob_HQ = "Tessabtob22k_HQ"
    Tessatransport_HQ = "Tessatransport22k_HQ"
    Anaisbtob_HQ = "Anaisbtob22k_HQ"
    Constance_HQ = "Constance22k_HQ"
    Ankebtob_HQ = "Ankebtob22k_HQ"
    Barbarabtob_HQ = "Barbarabtob22k_HQ"
    Ida_HQ = "Ida22k_HQ"
    Gosia_HQ = "Gosia22k_HQ"
    Lena_HQ = "Lena22k_HQ"
    Anabtob_HQ = "Anabtob22k_HQ"
    Elenabtob_HQ = "Elenabtob22k_HQ"
    Zeynep_HQ = "Zeynep22k_HQ"
    Lily_HQ = "Lily22k_HQ"
    Taylor_HQ = "Taylor22k_HQ"
    Jalal_NV = "Jalal22k_NV"
    Christinabtob_NT = "Christinabtob22k_NT"
    Gabriela_NV = "Gabriela22k_NV"
    Sophiabtob_NV = "Sophiabtob22k_NV"
    TaylorEnglish_NT = "TaylorEnglish22k_NT"
    RikkeTransport_NT = "RikkeTransport22k_NT"
    Tessabtob_NT = "Tessabtob22k_NT"
    Anaisbtob_NV = "Anaisbtob22k_NV"
    Constance_NV = "Constance22k_NV"
    TaylorFrench_NT = "TaylorFrench22k_NT"
    Ankebtob_NV = "Ankebtob22k_NV"
    TaylorGerman_NT = "TaylorGerman22k_NT"
    Barbarabtob_NV = "Barbarabtob22k_NV"
    TaylorItalian_NT = "TaylorItalian22k_NT"
    Biera_NT = "Biera22k_NT"
    Elle_NT = "Elle22k_NT"
    Ida_NT = "Ida22k_NT"
    Gosia_NV = "Gosia22k_NV"
    Lena_NT = "Lena22k_NT"
    Anabtob_NV = "Anabtob22k_NV"
    Elenabtob_NV = "Elenabtob22k_NV"
    TaylorSpanish_NT = "TaylorSpanish22k_NT"
    TaylorSwedish_NT = "TaylorSwedish22k_NT"
    Zeynep_NT = "Zeynep22k_NT"
    Lily_NV = "Lily22k_NV"
    Taylor_NV = "Taylor22k_NV"
    TaylorUSSpanish_NT = "TaylorUSSpanish22k_NT"
    Leila_HQ = "Leila22k_HQ"
    Mehdi_HQ = "Mehdi22k_HQ"
    Nizar_HQ = "Nizar22k_HQ"
    Salma_HQ = "Salma22k_HQ"
    Nizareng_HQ = "Nizareng22k_HQ"
    Lisa_HQ = "Lisa22k_HQ"
    Tyler_HQ = "Tyler22k_HQ"
    Jeroen_HQ = "Jeroen22k_HQ"
    JeroenHappy_HQ = "JeroenHappy22k_HQ"
    JeroenSad_HQ = "Jeroensad22k_HQ"
    Sofie_HQ = "Sofie22k_HQ"
    Zoe_HQ = "Zoe22k_HQ"
    AliceBE_HQ = "Alice-BE22k_HQ"
    AnaisBE_HQ = "Anais-BE22k_HQ"
    AntoineBE_HQ = "Antoine-BE22k_HQ"
    BrunoBE_HQ = "Bruno-BE22k_HQ"
    ClaireBE_HQ = "Claire-BE22k_HQ"
    JulieBE_HQ = "Julie-BE22k_HQ"
    ManonBE_HQ = "Manon-BE22k_HQ"
    MargauxBE_HQ = "Margaux-BE22k_HQ"
    Marcia_HQ = "Marcia22k_HQ"
    Sergio_HQ = "Sergio22k_HQ"
    Graham_HQ = "Graham22k_HQ"
    Lucy_HQ = "Lucy22k_HQ"
    Peter_HQ = "Peter22k_HQ"
    PeterHappy_HQ = "PeterHappy22k_HQ"
    PeterSad_HQ = "Petersad22k_HQ"
    QueenElizabeth_HQ = "QueenElizabeth22k_HQ"
    Rachel_HQ = "Rachel22k_HQ"
    Melany_HQ = "Melany22k_HQ"
    Anthony_HQ = "Anthony22k_HQ"
    Louise_HQ = "Louise22k_HQ"
    Melanie_HQ = "Melanie22k_HQ"
    Laia_HQ = "Laia22k_HQ"
    Eliska_HQ = "Eliska22k_HQ"
    Mette_HQ = "Mette22k_HQ"
    Rasmus_HQ = "Rasmus22k_HQ"
    Rikke_HQ = "Rikke22k_HQ"
    Daan_HQ = "Daan22k_HQ"
    Femke_HQ = "Femke22k_HQ"
    Jasmijn_HQ = "Jasmijn22k_HQ"
    Max_HQ = "Max22k_HQ"
    Hanna_HQ = "Hanna22k_HQ"
    Hanus_HQ = "Hanus22k_HQ"
    Samuel_HQ = "Samuel22k_HQ"
    Sanna_HQ = "Sanna22k_HQ"
    Alice_HQ = "Alice22k_HQ"
    Anais_HQ = "Anais22k_HQ"
    Antoine_HQ = "Antoine22k_HQ"
    AntoineFromAfar_HQ = "AntoineFromAfar22k_HQ"
    AntoineHappy_HQ = "AntoineHappy22k_HQ"
    AntoineSad_HQ = "Antoinesad22k_HQ"
    AntoineUpClose_HQ = "AntoineUpClose22k_HQ"
    Bruno_HQ = "Bruno22k_HQ"
    Claire_HQ = "Claire22k_HQ"
    Julie_HQ = "Julie22k_HQ"
    Manon_HQ = "Manon22k_HQ"
    Margaux_HQ = "Margaux22k_HQ"
    MargauxHappy_HQ = "MargauxHappy22k_HQ"
    MargauxSad_HQ = "Margauxsad22k_HQ"
    Andreas_HQ = "Andreas22k_HQ"
    Claudia_HQ = "Claudia22k_HQ"
    ClaudiaSmile_HQ = "ClaudiaSmile22k_HQ"
    Julia_HQ = "Julia22k_HQ"
    Klaus_HQ = "Klaus22k_HQ"
    Sarah_HQ = "Sarah22k_HQ"
    Kal_HQ = "Kal22k_HQ"
    Dimitris_HQ = "Dimitris22k_HQ"
    DimitrisHappy_HQ = "DimitrisHappy22k_HQ"
    DimitrisSad_HQ = "Dimitrissad22k_HQ"
    Vidhi_HQ = "Vidhi22k_HQ"
    Deepa_HQ = "Deepa22k_HQ"
    Vidhienglish_HQ = "Vidhienglish22k_HQ"
    Chiara_HQ = "Chiara22k_HQ"
    Fabiana_HQ = "Fabiana22k_HQ"
    Vittorio_HQ = "Vittorio22k_HQ"
    Sakura_HQ = "Sakura22k_HQ"
    Minji_HQ = "Minji22k_HQ"
    Lulu_HQ = "Lulu22k_HQ"
    Bente_HQ = "Bente22k_HQ"
    Kari_HQ = "Kari22k_HQ"
    Olav_HQ = "Olav22k_HQ"
    Ania_HQ = "Ania22k_HQ"
    Piotr_HQ = "Piotr22k_HQ"
    Celia_HQ = "Celia22k_HQ"
    Isabel_HQ = "Isabel22k_HQ"
    Alyona_HQ = "Alyona22k_HQ"
    Mia_HQ = "Mia22k_HQ"
    Rhona_HQ = "Rhona22k_HQ"
    Antonio_HQ = "Antonio22k_HQ"
    Ines_HQ = "Ines22k_HQ"
    Maria_HQ = "Maria22k_HQ"
    Elin_HQ = "Elin22k_HQ"
    Emil_HQ = "Emil22k_HQ"
    Emma_HQ = "Emma22k_HQ"
    Erik_HQ = "Erik22k_HQ"
    Ipek_HQ = "Ipek22k_HQ"
    Darius_HQ = "Darius22k_HQ"
    Karen_HQ = "Karen22k_HQ"
    Kenny_HQ = "Kenny22k_HQ"
    Laura_HQ = "Laura22k_HQ"
    Micah_HQ = "Micah22k_HQ"
    Nelly_HQ = "Nelly22k_HQ"
    Rod_HQ = "Rod22k_HQ"
    Ryan_HQ = "Ryan22k_HQ"
    Saul_HQ = "Saul22k_HQ"
    Sharon_HQ = "Sharon22k_HQ"
    Tamira_HQ = "Tamira22k_HQ"
    Tracy_HQ = "Tracy22k_HQ"
    Will_HQ = "Will22k_HQ"
    WillBadGuy_HQ = "WillBadGuy22k_HQ"
    WillFromAfar_HQ = "WillFromAfar22k_HQ"
    WillHappy_HQ = "WillHappy22k_HQ"
    WillLittleCreature_HQ = "WillLittleCreature22k_HQ"
    WillOldMan_HQ = "WillOldMan22k_HQ"
    WillSad_HQ = "Willsad22k_HQ"
    WillUpClose_HQ = "WillUpClose22k_HQ"
    Rodrigo_HQ = "Rodrigo22k_HQ"
    Rosa_HQ = "Rosa22k_HQ"
    Leila_NV = "Leila22k_NV"
    Mehdi_NV = "Mehdi22k_NV"
    Nizar_NV = "Nizar22k_NV"
    Salma_NV = "Salma22k_NV"
    Nizareng_NV = "Nizareng22k_NV"
    Lisa_NV = "Lisa22k_NV"
    Tyler_NV = "Tyler22k_NV"
    Jeroen_NT = "Jeroen22k_NT"
    JeroenHappy_NT = "JeroenHappy22k_NT"
    JeroenSad_NT = "JeroenSad22k_NT"
    Sofie_NT = "Sofie22k_NT"
    Zoe_NT = "Zoe22k_NT"
    AliceBE_NT = "Alice-BE22k_NT"
    AnaisBE_NT = "Anais-BE22k_NT"
    AntoineBE_NT = "Antoine-BE22k_NT"
    BrunoBE_NT = "Bruno-BE22k_NT"
    ClaireBE_NT = "Claire-BE22k_NT"
    JulieBE_NT = "Julie-BE22k_NT"
    ManonBE_NT = "Manon-BE22k_NT"
    MargauxBE_NT = "Margaux-BE22k_NT"
    Marcia_NV = "Marcia22k_NV"
    Sergio_NV = "Sergio22k_NV"
    Graham_NV = "Graham22k_NV"
    Lucy_NV = "Lucy22k_NV"
    Peter_NV = "Peter22k_NV"
    PeterHappy_NV = "PeterHappy22k_NV"
    PeterSad_NV = "PeterSad22k_NV"
    QueenElizabeth_NV = "QueenElizabeth22k_NV"
    Rachel_NV = "Rachel22k_NV"
    Melany_NV = "Melany22k_NV"
    Anthony_NV = "Anthony22k_NV"
    Louise_NV = "Louise22k_NV"
    Melanie_NV = "Melanie22k_NV"
    Laia_NT = "Laia22k_NT"
    Eliska_NT = "Eliska22k_NT"
    Mette_NT = "Mette22k_NT"
    Rasmus_NT = "Rasmus22k_NT"
    Rikke_NT = "Rikke22k_NT"
    Daan_NT = "Daan22k_NT"
    Femke_NT = "Femke22k_NT"
    Jasmijn_NT = "Jasmijn22k_NT"
    Max_NT = "Max22k_NT"
    Hanna_NT = "Hanna22k_NT"
    Hanus_NT = "Hanus22k_NT"
    Samuel_NT = "Samuel22k_NT"
    Sanna_NV = "Sanna22k_NV"
    Alice_NV = "Alice22k_NV"
    Anais_NV = "Anais22k_NV"
    Antoine_NV = "Antoine22k_NV"
    AntoineFromAfar_NV = "AntoineFromAfar22k_NV"
    AntoineHappy_NV = "AntoineHappy22k_NV"
    AntoineSad_NV = "AntoineSad22k_NV"
    Bruno_NV = "Bruno22k_NV"
    Claire_NV = "Claire22k_NV"
    Julie_NV = "Julie22k_NV"
    Manon_NV = "Manon22k_NV"
    Margaux_NV = "Margaux22k_NV"
    MargauxHappy_NV = "MargauxHappy22k_NV"
    MargauxSad_NV = "MargauxSad22k_NV"
    Andreas_NV = "Andreas22k_NV"
    Claudia_NV = "Claudia22k_NV"
    ClaudiaSmile_NV = "ClaudiaSmile22k_NV"
    Julia_NV = "Julia22k_NV"
    Klaus_NV = "Klaus22k_NV"
    Sarah_NV = "Sarah22k_NV"
    Kal_NT = "Kal22k_NT"
    Dimitris_NT = "Dimitris22k_NT"
    DimitrisHappy_NT = "DimitrisHappy22k_NT"
    DimitrisSad_NT = "Dimitrissad22k_NT"
    Vidhi_NT = "Vidhi22k_NT"
    Deepa_NT = "Deepa22k_NT"
    Vidhienglish_NT = "Vidhienglish22k_NT"
    Chiara_NV = "Chiara22k_NV"
    Fabiana_NV = "Fabiana22k_NV"
    Vittorio_NV = "Vittorio22k_NV"
    Sakura_NT = "Sakura22k_NT"
    Minji_NT = "Minji22k_NT"
    Lulu_NT = "Lulu22k_NT"
    Bente_NT = "Bente22k_NT"
    Kari_NT = "Kari22k_NT"
    Olav_NT = "Olav22k_NT"
    Ania_NV = "Ania22k_NV"
    Piotr_NV = "Piotr22k_NV"
    Isabel_NV = "Isabel22k_NV"
    Rui_HQ = "Rui22k_HQ"
    Rui_NV = "Rui22k_NV"
    Rui_NT = "Rui22k_NT"
    Alyona_NT = "Alyona22k_NT"
    Mia_NT = "Mia22k_NT"
    Rhona_NV = "Rhona22k_NV"
    Antonio_NV = "Antonio22k_NV"
    Ines_NV = "Ines22k_NV"
    Maria_NV = "Maria22k_NV"
    Elin_NV = "Elin22k_NV"
    Emil_NV = "Emil22k_NV"
    Emma_NV = "Emma22k_NV"
    Erik_NV = "Erik22k_NV"
    Ipek_NT = "Ipek22k_NT"
    Darius_NV = "Darius22k_NV"
    Karen_NV = "Karen22k_NV"
    Laura_NV = "Laura22k_NV"
    Micah_NV = "Micah22k_NV"
    Rod_NV = "Rod22k_NV"
    Ryan_NV = "Ryan22k_NV"
    Saul_NV = "Saul22k_NV"
    Sharon_NV = "Sharon22k_NV"
    Tamira_NV = "Tamira22k_NV"
    Tracy_NV = "Tracy22k_NV"
    Will_NV = "Will22k_NV"
    WillBadGuy_NV = "WillBadGuy22k_NV"
    WillFromAfar_NV = "WillFromAfar22k_NV"
    WillHappy_NV = "WillHappy22k_NV"
    WillLittleCreature_NV = "WillLittleCreature22k_NV"
    WillOldMan_NV = "WillOldMan22k_NV"
    WillSad_NV = "WillSad22k_NV"
    WillUpClose_NV = "WillUpClose22k_NV"
    Rodrigo_NV = "Rodrigo22k_NV"
    Rosa_NV = "Rosa22k_NV"

__session__ = __requests__.session()
__url1__ = 'https://www.acapela-group.com/wp-json/acapela/v1/get_accldcfg'
__headers1__ = {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.6",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "sec-ch-ua": '"Chromium";v="142", "Brave";v="142", "Not_A Brand";v="99"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "sec-gpc": "1",
    "referer": "https://www.acapela-group.com/demos/"
}
__url2__ = 'https://www.acapela-cloud.com/api/command/'
__headers2__ = {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.6",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "priority": "u=1, i",
    "sec-ch-ua": '"Chromium";v="142", "Brave";v="142", "Not_A Brand";v="99"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site",
    "sec-gpc": "1",
    "referer": "https://www.acapela-group.com/"
}

def requestTTS(text: str, voice = Voice.Lily_HQ):
    res = __session__.get(__url1__, headers=__headers1__)
    token = res.json()['token']
    params = { 'voice': voice.value, 'text': text, 'output': 'stream', 'type': 'mp3', 'samplerate': '22050', 'token': token }
    res = __session__.get(__url2__, headers=__headers2__, params=params)
    return res.content