name: Build
on:
  push:
    branches:
      - 'gh-pages'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Prepare and deploy
        if: ${{ steps.regex-match.outputs.match != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm i
          npx ng deploy --name="Sumanth Perambuduri" --email=35676632+supersu-man@users.noreply.github.com --no-silent      